# Generated by Django 4.0.2 on 2022-02-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img')),
                ('titulo', models.CharField(max_length=25)),
                ('descripción', models.CharField(max_length=60)),
                ('boton', models.CharField(default='Continua leyendo', max_length=20)),
                ('articulo', models.TextField()),
            ],
        ),
    ]
