# Generated by Django 4.0.2 on 2022-02-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugias',
            name='descripción',
        ),
        migrations.AddField(
            model_name='cirugias',
            name='descripcion',
            field=models.CharField(default='Escribe un texto...', max_length=120),
        ),
    ]
