# Generated by Django 4.0.2 on 2022-02-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_cirugias_descripción_cirugias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='descripcion',
            field=models.CharField(default='Escribe un texto...', max_length=500),
        ),
    ]
