# Generated by Django 4.0.2 on 2022-02-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_cirugias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='descripcion',
            field=models.CharField(default='Escribe un texto...', max_length=600),
        ),
    ]
