# Generated by Django 4.0.2 on 2022-02-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_cirugias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='articulo',
            field=models.TextField(default='Escribe un artículo...'),
        ),
    ]
