# Generated by Django 4.0.2 on 2022-02-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_equipo_padecimientos_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
