# Generated by Django 4.0.2 on 2022-02-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_servicios_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
