# Generated by Django 4.0.2 on 2022-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_equipo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugias',
            name='url',
            field=models.SlugField(default='None'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='url',
            field=models.SlugField(default='None'),
        ),
        migrations.AddField(
            model_name='padecimientos',
            name='url',
            field=models.SlugField(default='None'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='url',
            field=models.SlugField(default='None'),
        ),
    ]
