# Generated by Django 4.0.1 on 2022-03-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
