# Generated by Django 4.0.1 on 2022-03-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_cirugias_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugias',
            name='intervalo',
            field=models.IntegerField(default=5000),
        ),
    ]
