# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-07 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='1', max_length=20)),
                ('imagen', models.ImageField(upload_to='img')),
                ('intervalo', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Cirugias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(default='Escribe un texto...', max_length=600)),
                ('boton', models.CharField(default='Continua leyendo', max_length=20)),
                ('articulo', models.TextField(default='Escribe un articulo...')),
                ('url', models.SlugField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(default='Escribe un texto...', max_length=600)),
                ('articulo', models.TextField(default='Escribe un articulo...')),
                ('url', models.SlugField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Padecimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img')),
                ('titulo', models.CharField(max_length=25)),
                ('descripcion', models.CharField(default='Escribe un texto...', max_length=600)),
                ('url', models.SlugField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(default='Escribe un texto...', max_length=600)),
                ('boton', models.CharField(default='Servicio', max_length=20)),
                ('url', models.SlugField(default='None')),
            ],
        ),
    ]
