# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-09 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padecimientos',
            name='descripcion',
            field=models.TextField(default='Escribe un articulo...'),
        ),
    ]
