# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-14 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20220310_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.TextField(default='Escribe un texto...'),
        ),
    ]
