# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-15 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220314_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='boton',
            field=models.CharField(default='Servicio', max_length=40),
        ),
    ]
