# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-15 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220315_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padecimientos',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
